"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oz&$fp-x_jnw)5*l12$!0j-bqf4k)$eor@i4i3*$72@scubpyt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tailwind_cli',
    'core',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.newsletter',  # Add this line to include the newsletter form in all templates
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration


STATICFILES_DIRS = [BASE_DIR / "assets"]



# SimpleUI Configuration
SIMPLEUI_CONFIG = {
    # Customizing the left sidebar menu
    'SYSTEM_KEEP': False,
    'MENU_KEEP': False,
    'SHOW_PERMS': True, # Helps you assign granular permissions to staff vs admins
    
    # Custom links and menus
    'MENUS': [
        {
            'name': 'UCPM Management',
            'icon': 'fas fa-church',
            'models': [
                {
                    'name': 'Leaders',
                    'icon': 'fas fa-users',
                    'url': '/admin/core/leader/'
                },
                {
                    'name': 'Milestones',
                    'icon': 'fas fa-flag',
                    'url': '/admin/core/milestone/'
                }
            ]
        },
        {
            'app': 'auth',
            'name': 'Access Control',
            'icon': 'fas fa-shield-alt',
            'models': [
                {'name': 'Users', 'icon': 'fas fa-user', 'url': '/admin/auth/user/'},
                {'name': 'Groups', 'icon': 'fas fa-users-cog', 'url': '/admin/auth/group/'},
            ]
        }
    ]
}

# Choose a default theme color
SIMPLEUI_DEFAULT_THEME = 'adminlte.css'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ucpm.movement@gmail.com'  # Replace with your actual Gmail
EMAIL_HOST_PASSWORD = 'bflikyksjjmditio'       # Paste your 16-character App Password here (no spaces)
DEFAULT_FROM_EMAIL = 'UCPM Prayer Movement <ucpm.movement@gmail.com>'

from django.contrib.admin.options import ActionLocation
from json import JSONEncoder

# Save the original default encoder method
_old_default = JSONEncoder.default

def _new_default(self, obj):
    if isinstance(obj, ActionLocation):
        return str(obj)  # or obj.value depending on how it's structured
    return _old_default(self, obj)

# Apply the patch globally to catch ActionLocation serialization errors
JSONEncoder.default = _new_default