# Generated by Django 6.1.1 on 2026-09-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_eventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
