# Generated by Django 6.1.1 on 2026-09-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_event_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='highlight_summary',
            field=models.TextField(blank=True, help_text='Summary or notes for past events', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recap_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/recaps/'),
        ),
        migrations.AddField(
            model_name='event',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Downloadable notes or media files', null=True, upload_to='events/resources/'),
        ),
    ]
