# Generated by Django 6.1.1 on 2026-09-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_size',
            field=models.CharField(blank=True, help_text='e.g., 2.4 MB or 45 MINS', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('audio', 'Audio / MP3'), ('video', 'Video')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check if this should appear in the top banner.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('prayer-guides', 'Prayer Guides'), ('leadership', 'Leadership Docs'), ('audio', 'Sermon Audio'), ('branding', 'Media & Branding'), ('reports', 'Chapter Reports')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(),
        ),
    ]
