# Generated by Django 6.1.1 on 2026-09-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_resource_file_size_resource_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste YouTube or Facebook video link here', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('prayer-guides', 'Prayer Guides'), ('leadership', 'Leadership Docs'), ('audio', 'Sermon Audio'), ('video', 'Sermon & Media Videos'), ('branding', 'Media & Branding'), ('reports', 'Chapter Reports')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_size',
            field=models.CharField(blank=True, help_text='e.g., 45 MINS or 2.4 MB', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('audio', 'Audio / MP3'), ('video', 'Video Link')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
