# Generated by Django 6.1.1 on 2026-09-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_resource_video_url_alter_resource_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(help_text='e.g., University of Nairobi CU', max_length=200)),
                ('secretary_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('report_file', models.FileField(upload_to='chapter_reports/')),
                ('testimony_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
