# Generated by Django 6.1.1 on 2026-09-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_region_alter_event_order_event_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrayerFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('zoom_link', models.URLField()),
                ('is_active', models.BooleanField(default=True, help_text='Check this to show this focus on the home page.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters_count', models.PositiveIntegerField(default=52)),
                ('regions_count', models.PositiveIntegerField(default=12)),
                ('patrons_count', models.PositiveIntegerField(default=150)),
                ('impacted_count', models.PositiveIntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(help_text='e.g., CU Chairperson, University of Nairobi', max_length=150)),
                ('quote', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonies/')),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
