# Generated by Django 6.1.1 on 2026-09-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_newslettercampaign_newslettersubscriber_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
                ('chairperson_name', models.CharField(max_length=255)),
                ('member_count', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('admission_number', models.CharField(max_length=100, unique=True)),
                ('whatsapp_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
